import type { Metadata } from 'next'
// import './globals.css'

// css
import "./assets/vendor/nucleo/css/nucleo.css";
// import "./assets/vendor/@fortawesome/fontawesome-free/css/all.min.css";
import "./assets/scss/argon-dashboard-react.scss";

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <head>
        <meta name="viewport" content="initial-scale=1, width=device-width" />
        <link 
          href="https://fonts.googleapis.com/css?family=Open+Sans&display=optional:300,400,600,700" rel="stylesheet"
        />
      </head>
      
      <body>{children}</body>
    </html>
  )
}